### ISSUE TITLE
Error in docker-compose logs

### ISSUE THREAD

**Issue by sinacek** [robertoachar/docker-rabbitmq-node#3]
Hi,
I run your docker example, but in logs a got error msg.

```
producer_1  | [nodemon] 1.18.4
producer_1  | [nodemon] to restart at any time, enter `rs`
producer_1  | [nodemon] watching: *.*
producer_1  | [nodemon] starting `node src/index.js`
producer_1  | module.js:549
producer_1  |     throw err;
producer_1  |     ^
producer_1  | 
producer_1  | Error: Cannot find module 'winston'
producer_1  |     at Function.Module._resolveFilename (module.js:547:15)
producer_1  |     at Function.Module._load (module.js:474:25)
producer_1  |     at Module.require (module.js:596:17)
producer_1  |     at require (internal/module.js:11:18)
producer_1  |     at Object.<anonymous> (/usr/src/app/src/index.js:1:79)
producer_1  |     at Module._compile (module.js:652:30)
producer_1  |     at Object.Module._extensions..js (module.js:663:10)
producer_1  |     at Module.load (module.js:565:32)
producer_1  |     at tryModuleLoad (module.js:505:12)
producer_1  |     at Function.Module._load (module.js:497:3)
producer_1  | [nodemon] app crashed - waiting for file changes before starting...
```

```consumer_1  | [nodemon] 1.18.4
consumer_1  | [nodemon] to restart at any time, enter `rs`
consumer_1  | [nodemon] watching: *.*
consumer_1  | [nodemon] starting `node src/index.js`
consumer_1  | module.js:549
consumer_1  |     throw err;
consumer_1  |     ^
consumer_1  | 
consumer_1  | Error: Cannot find module 'winston'
consumer_1  |     at Function.Module._resolveFilename (module.js:547:15)
consumer_1  |     at Function.Module._load (module.js:474:25)
consumer_1  |     at Module.require (module.js:596:17)
consumer_1  |     at require (internal/module.js:11:18)
consumer_1  |     at Object.<anonymous> (/usr/src/app/src/index.js:1:79)
consumer_1  |     at Module._compile (module.js:652:30)
consumer_1  |     at Object.Module._extensions..js (module.js:663:10)
consumer_1  |     at Module.load (module.js:565:32)
consumer_1  |     at tryModuleLoad (module.js:505:12)
consumer_1  |     at Function.Module._load (module.js:497:3)
consumer_1  | [nodemon] app crashed - waiting for file changes before starting...```

**Comment by robertoachar** [comment]
Hi, thanks for reaching out.

Dependencies are missing on both projects. Change to `consumer` directory and run `npm install` then do it the same on `producer` directory too. Go back to root directory and you are good to go.

Sorry about that, I'll improve the docs.

**Comment by sinacek** [comment]
I would like just run docker without installation of any other dependencies, that is the reason why I would like use docker instead of run on my local.

**Comment by robertoachar** [comment]
I understand. The problem is that whenever you change the code, you will have to generate a new image. This project is prepared to monitor code changes and restart applications.

You can change the Docker file of both projects to not use volumes. Copy the contents of the directories and run `npm install` right in the Docker image. Remove the volumes on `docker-compose` file as well.

**Comment by sinacek** [comment]
Ok :)
